version: '3.8'

services:
  app:
    build: .
    container_name: user-manager-app
    ports:
      - '5173:5173'
    environment:
      - VITE_API_URL=http://localhost:8000
    networks:
      - user-service-network

networks:
  user-service-network:
    external: true
    name: user-service_user-service-network
