services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5173:80'
    environment:
      - VITE_USER_SERVICE_URL=http://localhost:8000/api
      - VITE_ENRICHMENT_SERVICE_URL=http://localhost:3000
